name = "spin-mama-casino-com-gr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spin-mama-casino.com.gr"
HMAC_KEY = "bac67bee41b22a12d5850ecc57f7278c7eb4c592ec30a85d9a01d805bafaad36"
COOKIE_NAME = "lpz"
PLAY_PATH = "join-now"
BUTTON_ID = "p26282dfd21d891cdb95915bfd08f0eb5"
GATE_SALT = "e240c61b5a9eaeae"
